### PR TITLE
Add DevDb

### PR DESCRIPTION
**Pull request by damms005**
Adds article for [a brand new VS Code extension](https://marketplace.visualstudio.com/items?itemName=damms005.devdb) that I launched v1 last Friday.

### CODE REVIEW

**Comment by benjamincrozat** [comment]
Hello!

Sorry for the delay.

I thought about it and I don't think I'm ready (yet) to accept entire articles. I still need to work some things out.

For now, I'd be happy to have your VS Code extension in my community links: https://benjamincrozat.com/links

Cheers!

Benjamin

**Comment by damms005** [comment]
Oh. I PR'ed because of the content of your readme. Noticed you [changed that about an hour ago](https://github.com/benjamincrozat/content/commit/e91055b74352a37f1370c8a9eafa1f89e5f25773).

Submitting the link now instead.

Thanks!

**Comment by benjamincrozat** [comment]
> Oh. I PR'ed because of the content of your readme. Noticed you [changed that about an hour ago](https://github.com/benjamincrozat/content/commit/e91055b74352a37f1370c8a9eafa1f89e5f25773).
> 
> 
> 
> Submitting the link now instead.
> 
> 
> 
> Thanks!

Sorry about that, this slipped off of my mind! Thanks again for your contribution, I really appreciate it!

**Comment by damms005** [comment]
Yeah it's all good man. At least I get to +1 my articles.

And yes, [I've noted you point](https://twitter.com/benjamincrozat/status/1744683880945209445).

Thanks again!

**Pull request closed without merging**
